version: '3.8'
services:
  balancer:
    container_name: balancer
    build:
      context: ./
      dockerfile: ./build/docker/service/Dockerfile
    ports: 
      - 8010:8010 
    restart: on-failure
    links:
      - balance-db
    depends_on:
      - balance-db

  balance-db:
    restart: always
    container_name: balance-db
    build: ./build/docker/db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=localhost
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres: